### ISSUE TITLE
Fails to build on Mac

### ISSUE THREAD

**Issue by eatspaint** [dzt/shopify-monitor-atc#2]
It looks like there are missing parts here. After filling in the description in `package.json`, Electron build looks like its hitting an error looking for assets.
```
$ build --mac
Rebuilding native production dependencies for darwin:x64
Packaging for darwin x64 using electron 1.6.0 to dist/mac
Error: ENOENT: no such file or directory, lstat '/Users/christianfuller/Desktop/shopify-monitor-atc/assets/logo.icns'
    at Error (native)
From previous event:
    at copy (/Users/christianfuller/Desktop/shopify-monitor-atc/node_modules/fs-extra-p/index.js:15:10)
    at Object.<anonymous> (/Users/christianfuller/Desktop/shopify-monitor-atc/node_modules/electron-builder/src/packager/mac.ts:143:19)
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Object.createApp (/Users/christianfuller/Desktop/shopify-monitor-atc/node_modules/electron-builder/out/packager/mac.js:133:21)
    at /Users/christianfuller/Desktop/shopify-monitor-atc/node_modules/electron-builder/src/platformPackager.ts:284:46
From previous event:
    at MacPackager.doPack (/Users/christianfuller/Desktop/shopify-monitor-atc/node_modules/electron-builder/out/platformPackager.js:324:11)
error Command failed with exit code 255.
```

**Comment by dzt** [comment]
O damn my fault their is no icon assets that's why! I'll be sure to update this repo later today
